cargo-features = ["strip"]

[workspace]
members = [
  "array_utils",
  "cli",
  "core",
  "dht",
  "magnet",
  "metainfo",
  "peers",
  "torrent-parser",
  "tracker",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
# opt-level = "z"
# panic = "abort"
