cargo-features = ["strip"]

[workspace]
members = [
  "bencode",
  "cli",
  "core",
  "magnet",
  "metainfo",
  "peers",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
# opt-level = "z"
# panic = "abort"