[package]
name = "leech"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.0.0-beta.4", features = ["wrap_help"] }
leech_core = { path = "../core", version = "0.1" }
tokio = { version = "1.12.0", features = ["macros", "parking_lot"] }
