[package]
name = "leech"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
clap = { version = "2.33.3", default-features = false }
leech_core = { path = "../core", version = "0.1" }
tokio = { version = "1.0.2", features = ["macros"] }

[[bin]]
name = "leech"
path = "main.rs"
doc = false