[package]
name = "leech"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2021"

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.0.0-rc.7", features = ["unicode", "wrap_help"] }
leech_core = { path = "../core" }
tokio = { version = "1.14.0", features = ["macros", "parking_lot"] }
