[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
bendy = "0.3.3"
bytes = "1.0.0"
hyper = "0.14.1"
rand = "0.8.0"
sha-1 = "0.9.2"
tokio = { version = "1.0.1", features = ["fs","net","rt-multi-thread","io-util"] }
url = "2.2.0"

[lib]
path = "lib.rs"
