[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
bytes = "1.0.1"
hyper = "0.14.9"
metainfo = { version = "0.1.0", path = "../metainfo" }
rand = "0.8.4"
tokio = { version = "1.7.1", features = ["io-util","fs","net","rt-multi-thread","parking_lot"] }
url = "2.2.2"
