[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
bendy = "0.4.0-beta.1"
bytes = "1.1.0"
peers = { version = "0.1.0", path = "../peers" }
form_urlencoded = "1.0.1"
hyper = { version = "0.14.13", default-features = false, features = ["client", "http1", "http2", "runtime", "stream", "tcp"] }
hyper-tls = "0.5.0"
metainfo = { version = "0.1.0", path = "../metainfo" }
rand = "0.8.4"
tokio = { version = "1.12.0", features = ["io-std", "io-util", "fs", "net", "rt-multi-thread", "parking_lot"] }
url = "2.2.2"
