[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <flickmor@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.35"
bytes = "0.6.0"
rand = "0.7.3"
serde = { version = "1.0.118", features = ["derive"] }
serde_bencode = "0.2.3"
serde_bytes = "0.11.5"
sha-1 = "0.9.2"
tokio = { version = "0.3.5", features = ["fs","macros","net","rt-multi-thread","io-util"] }
url = "2.2.0"

[lib]
path = "lib.rs"
