[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
bendy = "0.4.0-beta.1"
bytes = "1.0.1"
hyper = "0.14.9"
rand = "0.8.4"
sha-1 = "0.9.6"
tokio = { version = "1.7.1", features = ["io-util","fs","net","rt-multi-thread","parking_lot"] }
url = "2.2.2"
