[package]
name = "leech_core"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
array_utils = { path = "../array_utils" }
bendy = "0.4.0-beta.1"
bytes = "1.1.0"
peers = { path = "../peers" }
form_urlencoded = "1.0.1"
futures-core = "0.3.17"
hyper = { version = "0.14.13", default-features = false, features = ["client", "http1", "http2", "runtime", "stream", "tcp"] }
hyper-tls = "0.5.0"
metainfo = { path = "../metainfo" }
nom = "7.0.0"
rand = "0.8.4"
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["io-std", "io-util", "fs", "net", "rt-multi-thread", "parking_lot"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.6.9", features = ["codec"] }
tracker = { path = "../tracker" }
url = "2.2.2"
