[package]
name = "torrent-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
bento = { git = "https://github.com/morr0ne/bento",  rev = "d07a693", features = ["url"] }
sha-1 = "0.10.0"
url =  "2.2.2"
