[package]
name = "torrent-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.49"
bento = { git = "https://github.com/morr0ne/bento",  rev = "a3cb8ee", features = ["url"] }
sha-1 = "0.9.8"
url =  "2.2.2"
