[package]
name = "torrent-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
bento = { git = "https://github.com/morr0ne/bento",  rev = "d07a693", features = ["url"] }
sha-1 = "0.10.0"
url =  "2.3.1"
